apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: tatoos-backend:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: tatoos-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: tatoos-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: tatoos-config
              key: DB_NAME
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: tatoos-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tatoos-secrets
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: tatoos-secrets
              key: JWT_SECRET
        - name: JWT_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: tatoos-config
              key: JWT_EXPIRES_IN
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: tatoos-secrets
              key: GEMINI_API_KEY
        - name: CAPTCHA_SECRET
          valueFrom:
            secretKeyRef:
              name: tatoos-secrets
              key: CAPTCHA_SECRET
        - name: CAPTCHA_VERIFY_URL
          valueFrom:
            configMapKeyRef:
              name: tatoos-config
              key: CAPTCHA_VERIFY_URL
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: tatoos-secrets
              key: CLOUDINARY_CLOUD_NAME
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: tatoos-secrets
              key: CLOUDINARY_API_KEY
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: tatoos-secrets
              key: CLOUDINARY_API_SECRET
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: tatoos-config
              key: PORT
        - name: NODE_ENV
          value: production
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
